name: Pre-commit
on:
  pull_request:
    branches: 'master'
jobs:
  pre-commit:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-python@v2
          with:
            python-version: '3.10'
            cache: pip
        - uses: actions/setup-node@v2
          with:
            node-version: "17"
            cache: npm
        - run: npm install
        - uses: pre-commit/action@v2.0.3
